# Generated by Django 2.2.3 on 2019-07-30 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20190730_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AddField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15,
                                   validators=[django.core.validators.RegexValidator(
                                       message="Phone number must be entered in the format: '+999999999'. "
                                               "Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
