# Generated by Django 2.2.3 on 2019-07-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
